### ISSUE TITLE
Add text alignment with classes to Classic block

### ISSUE THREAD

**Issue by djmtype** [mrwweb/mrw-web-design-simple-tinymce#26]
I can understand why you may have left out the 3 alignment options off the Classic block editor because WP's flavor of TinyMCE  adds inline styles instead of classes which really sucks. 

I tried looking for ways of replacing the inline styles of text alignment with class names, but had no luck. 

This would be great as oppose to having these listed under Formats select.

**Comment by mrwweb** [comment]
@djmtype. Thanks for the suggestion.

My primary goal with this plugin is to remove the cruft and only modify features in limited circumstances (like styling the "Save Draft" button in the Block Editor). Your request, while a good one, is just a little too far out of scope here for me to consider adding, and I also am 100% focused on the block editor for future development.

The good news is that if there's a plugin that adds those buttons, it should be compatible with this plugin and you could use the `mce_buttons` filter to bring those buttons back if needed.

Thanks again for chiming in, and happy site building!
