### ISSUE TITLE
Code quality feedback request; example PHP snippet used to hide/unhide selected blocks and features

### ISSUE THREAD

**Issue by oldrup** [mrwweb/mrw-web-design-simple-tinymce#76]
Hey! Testing this little gem of a plugin on a handful of sites. 

Of course, the required blocks, differ from project to project, and for the sites I maintain, I have added and removed blocks to make the editing experience as simple as possible, and reduce cognitive strain for editors - and I.

To filter the particular blocks I need, I've ended up with the code below.

As I'm not an experienced PHP developer at all - would you mind taking a look at it, and give me a heads-up if there are any obvious flaws? When I feel confident that the snippet is ok, I'll share it in a blog post about MRW Simplified Editor. The plugin deserves some attention.

```php

<?php

// MRW Simplified Editor; Unhide specific inline options in the block editor

add_filter("mrw_hidden_block_editor_settings", "wp231202_unhide_inline");
function wp231202_unhide_inline($features)
{
    // Unhide the kbd and code html elements, I use those :)
    return array_diff($features, ["keyboard", "inline-code"]);
}

// MRW Simplified Editor; Unhide and hide selected blocks from the block-editor

add_filter("mrw_hidden_blocks", "wp231210_unhide_and_hide_blocks", 10, 2);
function wp231210_unhide_and_hide_blocks($blocks, $context)
{
    // Unhide the following blocks (which are hidden by default)
    $blocks = array_diff($blocks, [
        "core/audio",
        "core/code",
        "core/details",
        "core/table",
        "core/video",
    ]);

    // In addition to the defaults, hide the following blocks
    $additional_blocks_to_hide = [
        "core/comment-author-name",
        "core/comment-content",
        "core/comment-date",
        "core/comment-edit-link",
        "core/comment-reply-link",
        "core/comments-title",
        "core/embed",
        "core/file",
        "core/template-part",
    ];

    return array_merge($blocks, $additional_blocks_to_hide);
}


// MRW Simplified Editor; Hide specific embeds in the block editor
// Note: Don't hide core/embed above, if you want to use embeds

add_filter("mrw_hidden_embeds", "wp231202_hide_embeds", 10, 2);
function wp231202_hide_embeds($hidden_embeds)
{
    // In addition to the defaults, hide the following unused embeds
    $new_embeds_to_hide = [
        "flickr",
        "imgur",
        "issuu",
        "kickstarter",
        "pinterest",
        "reddit",
        "screencast",
        "scribd",
        "slideshare",
        "soundcloud",
        "speaker-deck",
        "spotify",
        "ted",
        "tiktok",
        "tumblr",
        "twitter",
        "wordpress",
    ];
    return array_merge($hidden_embeds, $new_embeds_to_hide);
}

// Plugin: https://wordpress.org/plugins/mrw-web-design-simple-tinymce/
// Full core block list: https://www.wpexplorer.com/wordpress-core-blocks-list/
```

**Comment by mrwweb** [comment]
Quick notes:

- Thanks so much for your eagerness to share the plugin. I'm glad you like it so much. Definitely send a link!
- Those `wp231210_` function prefixes are what I used from the support thread you opened on wordpress.org. I'd recommend making them specific to you / your theme. Maybe `oldrup_`? You could also consider using a namespace and then you wouldn't need a prefix.
- If you want to meet WordPress.org coding standards for arrays, you could switch from the short array syntax (`[ 'one', 'two' ]`) to the longer one (`array( 'one', 'two' )`). I tend to use the shortones in my personal projects but shouldn't use them out in public like that!

On a separate note, I'm surprised you needed to hide those comment blocks which are only visible in the Site Editor. If you're seeing them in the Block Editor then there may be a bug.

**Comment by oldrup** [comment]
Hmmm 🤔

Will share, for sure!

I prefixed as suggested, as I have no idea what namespaces are (and given the extent of this little "project", I think the prefixes will do just fine)

I definitely would like to meet coding standards, that's partly why I'm asking. Only interested in sharing working and harmless code if at all possible. Odd thing though, the WP Codebox plugin I use for these snippets, automatically replaces my [long syntax](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#declaring-arrays) arrays with the short bracket version, when I click "format code" ... Not polite at all :)
![image](https://github.com/mrwweb/mrw-simplified-editor-wordpress/assets/17141205/fe6cd023-4c35-4542-bf43-e2c7944ae386)

Regarding the comment blocks - can they be exposed by my Blocksy Theme which is a classic/hybrid theme? It's possible to create "template parts" in Blocksy using their hooks / dynamic blocks system - I can imagine they'd want to make these core blocks available for this. 

Reminding me, I should test my code snippet with other themes. Thanks :)

**Comment by oldrup** [comment]
Oh, here's the list in the block inserter when editing a page in Blocksy
![image](https://github.com/mrwweb/mrw-simplified-editor-wordpress/assets/17141205/ca4d0cfc-2086-4517-83e0-8f4406a5052e)

**Comment by oldrup** [comment]
Screenshot of block inserter when editing pages in Blocksy 
![image](https://github.com/mrwweb/mrw-simplified-editor-wordpress/assets/17141205/22ae746e-65c7-46bd-b2b3-963b25f0d2e9)

**Comment by mrwweb** [comment]
> I prefixed as suggested, as I have no idea what namespaces are (and given the extent of this little "project", I think the prefixes will do just fine)

No worries. Prefixes are great!

> automatically replaces my [long syntax](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#declaring-arrays) arrays with the short bracket version,

Interesting. It's not a huge problem, just thought I'd flag it since you asked. I do find the short syntax more readable, so it's not a horrible thing to publish it that way!

> Screenshot of block inserter when editing pages in Blocksy

I just ran MRW Simplified Editor with Blocksy and WordPress 6.4 and did not see all those blocks. I'm wondering if that's from a site that doesn't have MRW Simplified Editor active?

Either way, I'm going to close this issue now that I've supplied the feedback you requested. If run into a situation where a theme or plugin is unexpectedly showing blocks you think should be hidden, please open a new issue.
