### ISSUE TITLE
consider hiding the font manager by default

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/mrw-web-design-simple-tinymce#81]
https://make.wordpress.org/core/2024/03/14/new-feature-font-library/#how-to-disable-the-font-library

**Comment by oldrup** [comment]
+1 to that. A great feat of the plugin, is the ability to "lock down" the class based styling for those not so savvy or even intimidated creators. As a developer/designer, it's my job to make the fonts available that are needed. As I'm still on a classic theme, the theme can do that, or as I'm experimenting with currently, make fonts available via theme.json.

![image](https://github.com/mrwweb/mrw-simplified-editor-wordpress/assets/17141205/2c547013-0135-463f-ab9f-27caa2912650)

![image](https://github.com/mrwweb/mrw-simplified-editor-wordpress/assets/17141205/18049b70-2d3f-4556-b67d-404d2f2af101)

A default hidden font manager, or a filter to hide it, is a great idea, in my opinion.

**Comment by mrwweb** [comment]
@oldrup Thanks for the feedback. One thing about the Font Manager in 6.5 is that I believe it's only visible for sites using the Site Editor. I'm curious if that changes your mind on whether it's necessary to hide by default. I'm leaning yes, but on the fence.

**Comment by oldrup** [comment]
Okay I'm stupid. I could just have tested it before commenting. I got a RC3 install for exactly that purpose ;)

You are absolutely right.

- The font manager tool is available under Apperance > Editor with a FSE theme like 2024
- The Apperance > Editor is not available for Editor roles (and below I assume)
- The Apperance > Editor is not available in my classic theme.

There does not appear to be any way to access the font manage tool from the post edit screen / block editor. Which makes perfectly good sense.

That also means, that editors won't drown in font options; installing fonts is up to the administrator.

All good 😊

**Comment by mrwweb** [comment]
Since this is only active with the Site Editor, I'm not going to worry about this. Closing. Can always reopen later.
